---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        name: ğŸ¶ Ruff lint
        args:
          - --fix

      - id: ruff-format
        name: ğŸ¶ Ruff format

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        name: â¬†ï¸  Upgrade Python syntax
        args:
          - --py312-plus

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        name: ğŸ—œï¸  Check for added large files

      - id: check-ast
        name: ğŸ Check python ast

      - id: check-builtin-literals
        name: ğŸ§ Check builtin type constructor use

      - id: check-case-conflict
        name: ğŸ”  Check for case conflicts

      - id: check-docstring-first
        name: â„¹ï¸  Check docstring is first

      - id: check-executables-have-shebangs
        name: ğŸ§ Check that executables have shebangs

      - id: check-shebang-scripts-are-executable
        name: ğŸ§ Check that scripts with shebangs are executable

      - id: check-merge-conflict
        name: ğŸ’¥ Check for merge conflicts

      - id: check-symlinks
        name: ğŸ”— Check for broken symlinks

      - id: check-toml
        name: âœ… Check toml

      - id: check-xml
        name: âœ… Check xml

      - id: check-yaml
        name: âœ… Check yaml

      - id: debug-statements
        name: ğŸ” Debug statements (Python)

      - id: destroyed-symlinks
        name: ğŸ”— Detect destroyed symlinks

      - id: detect-private-key
        name: ğŸ•µï¸  Detect private key

      - id: end-of-file-fixer
        name: â®  Fix End of Files

      - id: fix-byte-order-marker
        name: ğŸ§ Fix utf-8 byte order marker

      - id: name-tests-test
        name: ğŸ”  Python tests naming
        args:
          - --pytest-test-first
        exclude: ^tests/syrupy.py

      - id: no-commit-to-branch
        name: ğŸ›‘ Don't commit to main branch

      - id: trailing-whitespace
        name: âœ„  Trim trailing whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: ğŸ’„ Ensuring files are prettier
        additional_dependencies:
          - prettier@3.3.3
          - prettier-plugin-sort-json@3.1.0
        exclude_types:
          - python
        exclude: ^uv.lock$

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: ğŸ—  Check YAML files with yamllint

  - repo: local
    hooks:
      - id: mypy
        name: ğŸ† Static type checking using mypy
        language: system
        types:
          - python
        entry: uv run mypy
        require_serial: true

      - id: prettier
        name: ğŸ’„ Ensuring files are prettier
        language: system
        types:
          - yaml
          - json
          - markdown
        entry: npm run prettier
        pass_filenames: false

      - id: pylint
        name: ğŸŒŸ Starring code with pylint
        language: system
        types:
          - python
        entry: uv run pylint

      - id: pytest
        name: ğŸ§ª Running tests and test coverage with pytest
        language: system
        types:
          - python
        entry: uv run pytest
        pass_filenames: false
